# Generated by Django 4.1.6 on 2023-09-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_allmovie_screenshot_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allmovie',
            name='Screenshot_img',
        ),
        migrations.AddField(
            model_name='allmovie',
            name='Screenshot_img',
            field=models.ManyToManyField(default=None, to='app1.screenshot'),
        ),
    ]
