# Generated by Django 4.1.6 on 2023-09-16 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_allmovie_screenshot_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allmovie',
            name='Screenshot_img',
        ),
        migrations.AddField(
            model_name='screenshot',
            name='movie_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app1.allmovie'),
        ),
    ]
