# Generated by Django 4.1.6 on 2023-09-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_allmovie_screenshot_img_screenshot_movie_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieComment',
        ),
    ]
