# Generated by Django 4.1.6 on 2023-10-12 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0011_moviecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mywebsite_feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_msg', models.TextField()),
                ('feedback_rating', models.PositiveIntegerField()),
                ('feedbackor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
